export enum ActivityType {
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_PASSWORD_CHANGED = 'AUTH_PASSWORD_CHANGED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  PERMISSION_CHANGED = 'PERMISSION_CHANGED',
}
